serviceA-v1:
    image: 'registry.cn-hangzhou.aliyuncs.com/jingshanlb/bluegreen-service-a:latest'
    labels:
        aliyun.scale: 3
        aliyun.routing.port_5000: servicea.local
serviceB-v1:
    image: 'registry.cn-hangzhou.aliyuncs.com/jingshanlb/bluegreen-service-b:latest'
    environment:
        - 'dep_endpoint=http://servicea.local'
    labels:
        aliyun.scale: 2
        aliyun.routing.port_5001: serviceb
    external_links:
        - "servicea.local"
